export const mobNames = [
    "Bat", "Blaze", "Bee", "Bogged", "Breeze", "Cat", "Cave Spider", "Chicken", "Cow", "Sniffer",
    "Creeper", "Dolphin", "Goat", "Panda", "Donkey", "Drowned", "Elder Guardian", "Egg", "End Crystal", "Ender Dragon",
    "Enderman", "Endermite", "Ender Pearl", "Evoker", "Fox", "Pufferfish", "Axolotl", "Ghast", "Piglin Brute", "Piglin",
    "Zombified Piglin", "Guardian", "Hoglin", "Horse", "Husk", "Ravager", "Iron Golem", "Snow Golem", "Llama", "Magma Cube",
    "Ocelot", "Phantom", "Parrot", "Slime", "Pig", "Painting", "Pillager", "Polar Bear", "Rabbit", "Sheep",
    "Vindicator", "Shulker", "Silverfish", "Skeleton", "Stray", "Spider", "Vex", "Witch", "Wither", "Wither Skeleton",
    "Wolf", "Zoglin", "Zombie Villager", "Zombie", "Experience Orb", "Dream", "Technoblade", "Overlord_Kaige", "Zhang_Ge's_Football_Dream"
];

export const environmentalDeathMessages = [
    "tried to swim in lava",
    "fell from a high place",
    "was squashed by a falling block",
    "starved to death",
    "suffocated in a wall",
    "was impaled by a Drowned",
    "fell out of the water",
    "fell off some vines",
    "fell off a ladder",
    "was impaled on a stalagmite",
    "was skewered by a falling stalactite",
    "was obliterated by a sonically-charged shriek",
    "froze to death",
    "withered away",
    "was pricked to death by a sweet berry bush",
    "fell out of the world",
    "burned to death",
    "walked into a danger zone",
    "discovered the floor was lava",
    "was killed by magic",
    "was struck by lightning",
    "walked into fire whilst fighting a Zombified Piglin",
    "went up in flames",
    "died",
    "experienced kinetic energy",
    "went off with a bang",
    "was fireballed by a Blaze",
    "was squashed by a falling block",
    "was blown up by a Creeper",
    "hit the ground too hard",
    "was killed by [Intentional Game Design]",
    "blew up",
    "drowned",
    "walked into a cactus while trying to escape a Husk",
    "was squashed by a falling anvil"
];