export const regularChatMessages = [
    "anyone got coal?",
    "u guys good on wood? i'm out",
    "need iron",
    "trading diamonds for enchanted books, any takers?",
    "gimme some redstone plz",
    "need obsidian bad, anyone?",
    "why is leather so hard to get",
    "going mining",
    "this cave is loaded",
    "mined all afternoon and got nothing",
    "trash game",
    "i have 20 iron u scared?",
    "wait this cat hits people??",
    "need food",
    "i'm starving",
    "more plz",
    "u guys staying on?",
    "need some torches",
    "let's brew some potions!",
    "gonna make some tipped arrows",
    "been grinding for enchanted books for ages",
    "use pistons",
    "got lots of wool",
    "we got a beacon yet?",
    "kinda sucks",
    "the iron farm is broken",
    "this villager is running all over the place",
    "mob next to u",
    "well hello there",
    "hehe",
    "k",
    "thoughts?",

    "my base is finished",
    "what material looks good for a roof?",
    "who broke my door??",
    "don't touch my stuff",
    "finally automated!",
    "damn, the villager breeder broke again",
    "built a mob farm, the rates are decent",
    "check out -340 80 1200, looks amazing",
    "i'm short on mats",
    "let's fence this area off",
    "place some torches, it's too dark",
    "can't see anything",

    "anyone for the nether?",
    "who has nether wart?",
    "got a bunch of skeletons on me",
    "a creeper blew me back to spawn",
    "there's a spawner here",
    "finally found a village",
    "this ravine is full of iron",
    "found the stronghold",
    "time for the ender dragon",
    "i'm lost af, help",
    "let's break this spawner",
    "cave spider spawner up ahead",
    "it's a mineshaft",
    "i see a temple",
    "looks like a temple",
    "ocean monument",
    "finally found a woodland mansion",
    "gonna feed the dolphins",
    "there's a shipwreck over there",
    "diamonds in the chest!",
    "found a bastion",
    "let's go farm blazes",
    "there's a brute inside",
    "vindicators hit so hard",
    "let's trigger a raid",
    "let's go",
    "get the crossbow",
    "time to trade some nautilus shells for a trident lol",
    "it's raining",
    "let's make an iron golem",
    "why is there a snow golem here",
    "witch hut",
    "pillager outpost!",
    "got a trial chambers map",
    "end city",
    "got the elytra!",

    "anyone on?",
    "the server's so laggy tonight",
    "did the server restart?",
    "where's spawn?",
    "how do i get home?",
    "who just flew past?",
    "afk don't kill me",
    "newbie here, can someone help?",
    "how do u play this game",
    "tps is a bit low",
    "bruh",
    "k",
    "nah",
    "hurry up",
    "someone's nearby",
    "get over here",
    "wth are you doing?",
    "can you stop randomly hitting people?",
    "this idiot",
    "are u crazy?",
    "gapple",
    "admin can i get perms?",
    "did you guys join the discord?",
    "i see someone",
    "omg",
    "mobs!",
    "Herobrine",
    "scared the hell out of me",
    "what happened?",
    "QwQ",
    "-_-",
    "oof",
    "i can't even",
    "stop chasing me",
    "AHHHHHHH",
    "nice",
    "lmao",
    "squeaker",
    "someone's wolf is going crazy",
    "i wanna pvp u",
    "I am Zhui Mu",
    "laaaaaag",
    "gg",

    "anyone see {real_player}?",
    "watch out for {real_player}, he's a troll",
    "{real_player} where are u",
    "found a {structure_name} at {structure_coords}",
    "team up for {structure_name} at {structure_coords}",
    "be careful, there's a dangerous {structure_name} at {structure_coords}"
];